Add missing image of img/dev/iMacIMAC-32.png
there was warning & error like this
Warning: No such file or directory while opening ../img/dev/iMacIMAC-32.png
Error: No or improper image file="../img/dev/iMacIMAC-32.png"
in label of node 10:dd:b1:XX:XX:XX

I have added image from: http://en.wikipedia.org/wiki/IMac
to fix this issue